name: ReSign vbmeta.img

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      rollback_index:
        description: "Rollback index to use (default: 0)"
        required: false
        default: "0"
        type: choice
        options:
          - 0
          - 12
          

jobs:
  sign-vbmeta:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python and avbtool
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip openssl
        pip3 install pycryptodome

    - name: Install avbtool
      run: |
        wget https://android.googlesource.com/platform/external/avb/+/refs/heads/main/avbtool.py?format=TEXT -O avbtool_base64
        base64 -d avbtool_base64 > avbtool
        chmod +x avbtool

    # Step 3: Verify the existing vbmeta.img
    - name: Verify vbmeta.img
      run: |
        ./avbtool info_image --image vbmeta.img || echo "vbmeta.img not found. Please upload it to the repository."

    # Step 4: Generate a signing key if it doesn't exist
    - name: Generate signing key
      run: |
        if [ ! -f "phh.pem" ]; then
          openssl genrsa -out phh.pem 2048
        fi

    # Step 5: Re-sign vbmeta.img
    - name: Re-sign vbmeta.img
      run: |
        ./avbtool make_vbmeta_image \
          --key phh.pem \
          --algorithm SHA256_RSA2048 \
          --flag 3 \
          --padding_size 4096 \
          --rollback_index ${{ inputs.rollback_index }} \
          --output vbmeta-signed.img
          
          
    # Step 6: Re-sign vbmeta.img
    - name: resize vbmeta-signed.img
      run: |
        ./avbtool add_hash_footer \
          --image vbmeta-signed.img \
          --partition_name vbmeta \
          --partition_size 8388608
          
          
    - name: Delete Footer
      run: |
        dd if=vbmeta-signed.img of=vbmeta_no_footer.img bs=1 count=$(( $(stat -c %s vbmeta-signed.img) - 4096 ))

    # Step 6: Upload the modified vbmeta.img
    - name: Upload vbmeta-signed.img To Artifact
      uses: actions/upload-artifact@v3
      with:
        name: vbmeta_no_footer.img
        path: vbmeta_no_footer.img
